// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjxs1TI2IA0JkfiyMdWQs2d1XxTfbRL-E',
    appId: '1:964424453388:web:18ac3ed1cc9fa3defd4d29',
    messagingSenderId: '964424453388',
    projectId: 'trust-med-e3c85',
    authDomain: 'trust-med-e3c85.firebaseapp.com',
    storageBucket: 'trust-med-e3c85.firebasestorage.app',
    measurementId: 'G-BE143N94XT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyUrTR3ZcXueu9YXB6u3eUyAKHTghD1Kk',
    appId: '1:964424453388:android:a5a6105ca5a50618fd4d29',
    messagingSenderId: '964424453388',
    projectId: 'trust-med-e3c85',
    storageBucket: 'trust-med-e3c85.firebasestorage.app',
  );
}
